// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUz41iQa8oSGBT7Z8_KjsY8le4Sus3Gt4',
    appId: '1:632994618408:web:ab9c50862e69dbb774291d',
    messagingSenderId: '632994618408',
    projectId: 'profile-38c46',
    authDomain: 'profile-38c46.firebaseapp.com',
    storageBucket: 'profile-38c46.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbli7z3cgJ4Lib6tLqOUGiYBydgzxgAww',
    appId: '1:632994618408:android:64bccbb008ac22f874291d',
    messagingSenderId: '632994618408',
    projectId: 'profile-38c46',
    storageBucket: 'profile-38c46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvfTXNxze84ZyREzSu70gT2JHdEILAc3Y',
    appId: '1:632994618408:ios:74450e919d1ddb9974291d',
    messagingSenderId: '632994618408',
    projectId: 'profile-38c46',
    storageBucket: 'profile-38c46.appspot.com',
    iosBundleId: 'com.example.secureprofile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvfTXNxze84ZyREzSu70gT2JHdEILAc3Y',
    appId: '1:632994618408:ios:74450e919d1ddb9974291d',
    messagingSenderId: '632994618408',
    projectId: 'profile-38c46',
    storageBucket: 'profile-38c46.appspot.com',
    iosBundleId: 'com.example.secureprofile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUz41iQa8oSGBT7Z8_KjsY8le4Sus3Gt4',
    appId: '1:632994618408:web:67e94387193fd52274291d',
    messagingSenderId: '632994618408',
    projectId: 'profile-38c46',
    authDomain: 'profile-38c46.firebaseapp.com',
    storageBucket: 'profile-38c46.appspot.com',
  );
}
